server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: auth-backend
  profiles:
    active: dev # ou prod selon le contexte

  datasource:
    driver-class-name: org.postgresql.Driver
  
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    cm.adcsa: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000 # 24h
    refresh-expiration: 2592000000 # 30 days
  
  security:
    max-login-attempts: 5
    account-lock-duration: 1800000 # 30 minutes
    session-timeout: 3600000 # 1 hour
