spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.1.10}:${DB_PORT:5432}/${DB_NAME:ged_adcsa}
    username: ${DB_USERNAME:backend_app}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    cm.adcsa: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours
